### ISSUE TITLE
uk-all-trends Missingness

### ISSUE THREAD

**Issue by M-Merciless** [datasciencecampus/google-mobility-reports-data#1]
Hi there,

(Great work by the way). I've been working with the above dataset and have noticed that following an unpivot function in R, there is a degree of missingness. The ID oclumns aren't of concern (they are the rows for the UK which have a pattern of NAs) but I wondered about the NAs in the data:

![uk-all-trends_missingness](https://user-images.githubusercontent.com/49126943/78637807-09583700-78a3-11ea-9f92-4ee506a74e09.png)

I can see that some of the Google charts in the original pdf stated that data was missing on certain dates, so this may explain the issue. But I wondered if the missing rows had been examined and used against the source data to gain insight into the accuracy of the OCR process? 

I've subsetted the data where the data column is NA and will attempt to attach. 

Apologies if this work has already been done and fantastic work turning this around so quickly.

**Comment by M-Merciless** [comment]
Unfortunately, the csv is not an acceptable filetype for attachment here. If needed I can upload elsewhere.

**Comment by alistair-ons** [comment]
Hi @M-Merciless 

The NAs are an issue with the source data. If you have a look at the pdf charts you'll see where there are NAs reported there are breaks in the series. One such pages there will be a warning *"Not enough data for this date: Currently, there is not enough data to provide a complete analysis of this place. Google needs a significant volume of data to generate an aggregated and anonymous view of trends."* Whilst we haven't checked every instance, we've spot checked a number to satisfy ourselves that this the source of the missing data rather than our processing. 

As you note, the NA for the ID is the national figure for which there isn't a representative code.
